// Conteúdo do portfólio. Para editar textos e projetos, mexa só aqui.

export const perfil = {
  nome: 'Matheus Gotardo',
  usuario: 'GotardoN1',
  email: 'luh20123@gmail.com',
  linkedin: 'https://www.linkedin.com/in/matheus-gotardo-680b3232b',
  github: 'https://github.com/GotardoN1',
  formacao: 'Bacharelado em Ciência da Computação (UNIANDRADE)',
  papeis: ['Infraestrutura & Redes', 'Dados & Business Intelligence', 'Automação & Software', 'Sistemas que rodam em produção'],
};

// Áreas: cada uma vira filtro, nó do mapa e comando do terminal
export const areas = [
  { id: 'producao', nome: 'Em produção', curto: 'Produção', cor: 'warm', texto: 'Sistemas usados todos os dias por uma rede de lojas de varejo.' },
  { id: 'software', nome: 'Software', curto: 'Software', cor: 'violet', texto: 'Aplicativos desktop e ferramentas internas.' },
  { id: 'web', nome: 'Web', curto: 'Web', cor: 'pink', texto: 'Sites e portais.' },
  { id: 'dados', nome: 'Dados & BI', curto: 'Dados', cor: 'sky', texto: 'Data warehouse, BI e machine learning.' },
  { id: 'infra', nome: 'Infra & Redes', curto: 'Infra', cor: 'accent', texto: 'Servidores, redes, deploy e monitoramento.' },
  { id: 'estudos', nome: 'Estudos', curto: 'Estudos', cor: 'stone', texto: 'Projetos acadêmicos e pesquisas.' },
];

export const projetos = [
  {
    slug: 'intranet',
    titulo: 'Intranet corporativa',
    icone: '🧭',
    areas: ['producao', 'web', 'infra'],
    privado: true,
    resumo: 'Portal interno completo: chamados com SLA, informativos, agenda, ativos de TI e monitoramento das lojas.',
    descricao: 'Portal que reúne o dia a dia da empresa num só lugar. Substituiu planilhas, um Google Sites e sistemas soltos por uma única intranet com permissões por setor.',
    destaques: [
      'Central de serviços com SLA, aprovações e filas por setor (TI, Logística e Marketing)',
      'Informativos integrados ao Google Drive, com leitura obrigatória',
      'Agenda, reserva de salas, pessoas e aniversariantes',
      'Controle de ativos e licenças e painel de monitoramento das lojas',
      '4 perfis de permissão e login Google restrito ao domínio da empresa',
      'CI no GitHub Actions publicando sozinho numa VM Proxmox; 180+ testes automatizados',
    ],
    stack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'OpenAPI', 'Docker', 'GitHub Actions', 'Proxmox'],
  },
  {
    slug: 'etiquetas',
    titulo: 'Etiquetas de estoque',
    icone: '🏷️',
    areas: ['producao', 'software'],
    privado: true,
    resumo: 'App desktop que unificou quatro ferramentas do estoque: etiquetas Zebra em ZPL e folhas de transporte.',
    descricao: 'Antes eram quatro programas diferentes para remanejo, transporte e impressão. Virou um único aplicativo, que acha a impressora certa sozinho.',
    destaques: [
      'Etiquetas em ZPL para impressoras Zebra, com detecção automática do modelo',
      'Calibração por régua impressa para cada rolo e impressora',
      'Folhas A4 de transporte em PDF, uma por volume',
      'Cadastros de lojas e transportadoras lidos do Google Drive',
      'Atualização automática e duas versões: Windows 10/11 e Windows 7/8/8.1',
    ],
    stack: ['Electron', 'JavaScript', 'ZPL', 'Google Drive', 'GitHub Releases'],
  },
  {
    slug: 'acesso-remoto',
    titulo: 'Acesso remoto',
    icone: '🖥️',
    areas: ['producao', 'software', 'infra'],
    privado: true,
    resumo: 'Cliente de suporte remoto às lojas sobre um servidor RustDesk próprio, no estilo TeamViewer.',
    descricao: 'Reescrevi a ferramenta antiga, que raspava o painel com um navegador automatizado, como um app leve com atualização automática.',
    destaques: [
      'Lojas e computadores organizados pelos grupos do servidor',
      'Instala e configura o RustDesk sozinho no computador do usuário',
      'Status do servidor em tempo real: verde, amarelo ou vermelho',
      'Atualização automática pelo GitHub Releases',
    ],
    stack: ['Electron', 'RustDesk', 'PowerShell', 'Node.js'],
  },
  {
    slug: 'g435',
    titulo: 'G435 Companion',
    icone: '🎧',
    areas: ['software'],
    repo: 'G435-Companion',
    resumo: 'Painel em português para o headset Logitech G435 no Windows: volume, microfone, conexão e bateria.',
    descricao: 'Reúne numa janela simples o que o Windows informa sobre o G435, com uma ilustração do fone que reage ao uso. Quando um dado não está disponível, o painel avisa em vez de inventar um valor.',
    destaques: [
      'Lê e ajusta o volume e o mute da saída e do microfone',
      'Identifica a conexão: USB/LIGHTSPEED ou Bluetooth',
      'Tenta ler a bateria pelo Bluetooth e explica quando não consegue',
      'Atualização pelo GitHub Releases',
    ],
    stack: ['C#', 'WinForms', 'Core Audio', 'Windows'],
  },
  {
    slug: 'planex',
    titulo: 'PlaneX',
    icone: '📊',
    areas: ['web'],
    repo: 'PlaneX',
    site: 'https://gotardon1.github.io/PlaneX/',
    resumo: 'Site de serviço de automação de planilhas, com uma demonstração interativa de antes e depois.',
    descricao: 'Apresenta a automação de Excel e Google Sheets. A demonstração mostra uma planilha manual virando relatório automático, com dados fictícios.',
    destaques: ['Demonstração interativa de planilha', 'Site estático: publica direto no GitHub Pages, sem compilação'],
    stack: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
  },
  {
    slug: 'msec',
    titulo: 'MSEC TEAM',
    icone: '🎮',
    areas: ['web'],
    repo: 'msecteam-site',
    site: 'https://gotardon1.github.io/msecteam-site/',
    resumo: 'Site da equipe de esports Me Sinto em Casa.',
    descricao: 'Site de apresentação da equipe de esports Me Sinto em Casa (MSEC TEAM).',
    destaques: ['Single-page em React', 'Publicado no GitHub Pages'],
    stack: ['TypeScript', 'React', 'GitHub Pages'],
  },
  {
    slug: 'bi-energia',
    titulo: 'BI e eficiência energética',
    icone: '☀️',
    areas: ['dados', 'estudos'],
    repo: 'bi-eficiencia-energetica',
    resumo: 'Data warehouse e dashboards para avaliar energia solar numa planta industrial em Salvador/BA.',
    descricao: 'Estudo de viabilidade de energia solar fotovoltaica em dois prédios de uma planta industrial: o administrativo e a unidade de produção principal.',
    destaques: ['Data warehouse em MySQL com esquema estrela', 'ETL em SQL', 'Cubo OLAP e dashboards no Power BI'],
    stack: ['MySQL', 'SQL', 'Star Schema', 'Power BI'],
  },
  {
    slug: 'recs',
    titulo: 'Sustentabilidade e RECs',
    icone: '🌱',
    areas: ['dados', 'estudos'],
    repo: 'sustentabilidade-energetica-recs',
    resumo: 'Engenharia de dados e BI para analisar a adoção de Certificados de Energia Renovável.',
    descricao: 'Analisa o consumo de energia e a adoção de RECs (Certificados de Energia Renovável) a partir de dados regionais, para apoiar decisões sustentáveis.',
    destaques: ['Filtragem de dados regionais', 'Modelagem de dados para BI'],
    stack: ['Engenharia de dados', 'BI', 'SQL'],
  },
  {
    slug: 'trena',
    titulo: 'Trena digital com ML',
    icone: '📏',
    areas: ['dados', 'estudos'],
    repo: 'trena-digital-ux-ml',
    resumo: 'Trena eletrônica que reconhece medidas escritas à mão com SVM e já entrega os dados digitados.',
    descricao: 'Proposta de UX para trenas eletrônicas. Profissionais de engenharia e arquitetura perdem tempo redigitando medições, e um modelo SVM reconhece as medidas manuscritas e as transforma em dados.',
    destaques: ['Classificação com SVM (Support Vector Machine)', 'Foco na experiência de quem mede em campo'],
    stack: ['Python', 'Machine Learning', 'SVM', 'UX'],
  },
  {
    slug: 'ocr-obras',
    titulo: 'Medição de obras com OCR',
    icone: '🏗️',
    areas: ['software', 'dados', 'estudos'],
    repo: 'medicao-obras-ocr',
    extra: { rotulo: 'Estudo e apresentação', url: 'https://github.com/GotardoN1/medicao-obras-ocr-estudo' },
    resumo: 'App desktop que lê medições anotadas em caderno e gera relatórios e orçamentos pela tabela SINAPI.',
    descricao: 'Feito para pequenas construtoras e autônomos, que ainda medem obras em caderno e calculadora. O modo semiautomático lê as anotações com OCR e organiza os dados pelas regras da tabela SINAPI.',
    destaques: ['OCR de medições manuscritas', 'Orçamento com base na tabela SINAPI', 'Pesquisa de campo com empresas do setor'],
    stack: ['Python', 'OCR', 'Desktop', 'SINAPI'],
  },
  {
    slug: 'colina',
    titulo: 'Rede do Supermercado Colina',
    icone: '🛒',
    areas: ['infra', 'estudos'],
    repo: 'rede-supermercado-colina',
    resumo: 'Projeto e simulação da rede de três unidades de um supermercado fictício em Curitiba, com IoT.',
    descricao: 'Planejamento e simulação de uma infraestrutura de rede completa: matriz e filiais interligadas, LAN e dispositivos IoT num cenário empresarial realista.',
    destaques: ['Três unidades interconectadas', 'LAN, roteamento e IoT', 'Simulação no Cisco Packet Tracer'],
    stack: ['Cisco Packet Tracer', 'Redes', 'IoT'],
  },
  {
    slug: 'grafo',
    titulo: 'Grafo Social',
    icone: '🕸️',
    areas: ['dados', 'estudos'],
    repo: 'grafo-social',
    resumo: 'Como a teoria dos grafos sustenta o Facebook: da matemática ao TAO e ao GraphQL.',
    descricao: 'Estudo aprofundado do "grafo social": modelagem matemática de pessoas e conexões e as tecnologias de backend da Meta que o sustentam.',
    destaques: ['Teoria dos grafos aplicada', 'TAO: cache distribuído de objetos e associações', 'GraphQL'],
    stack: ['Python', 'Grafos', 'GraphQL'],
  },
  {
    slug: 'o3de',
    titulo: 'Pong no Open 3D Engine',
    icone: '🏓',
    areas: ['estudos'],
    repo: 'pong-o3de',
    resumo: 'Estudo do motor open source O3DE com a implementação de um Pong, feito em equipe.',
    descricao: 'Estudo do Open 3D Engine, motor 3D modular e multiplataforma mantido pela Linux Foundation, com a implementação de um Pong.',
    destaques: ['Motor 3D open source (Apache 2.0)', 'Trabalho em equipe'],
    stack: ['O3DE', 'Game dev'],
    equipe: 'Fabrício Corrêa, Matheus Gotardo e Nicole Diniz',
  },
  {
    slug: 'sequencia',
    titulo: 'Repita a Sequência',
    icone: '🧠',
    areas: ['software', 'estudos'],
    repo: 'jogo-repita-a-sequencia',
    resumo: 'Jogo de memória em C para crianças de 9 a 12 anos, com sequências de cores e sons.',
    descricao: 'Projeto do curso de Ciência da Computação na UNIANDRADE. O jogo estimula a memória com sequências de cores e sons.',
    destaques: ['Planejamento e cronograma', 'Requisitos funcionais e não funcionais', 'Fluxograma e implementação em C'],
    stack: ['C', 'Modelagem', 'Requisitos'],
  },
];

export const etapas = [
  { titulo: 'Entender', texto: 'Converso com quem usa o processo e anoto onde está o retrabalho. O problema certo vale mais que a ferramenta certa.' },
  { titulo: 'Construir', texto: 'Começo pelo mínimo que resolve, com testes automatizados e documentação em português para quem vai usar.' },
  { titulo: 'Publicar', texto: 'Entrega automática pelo GitHub: o código passa pela CI e vai sozinho para produção, sempre com nota de versão.' },
  { titulo: 'Acompanhar', texto: 'Monitoramento, backup e atualização automática, para ninguém ficar parado esperando suporte.' },
];

export const stack = [
  { grupo: 'Infraestrutura', itens: ['Proxmox', 'Linux', 'Docker', 'pfSense', 'Windows'] },
  { grupo: 'Redes', itens: ['Cisco', 'NAT', 'Monitoramento', 'Grafana'] },
  { grupo: 'Dados & BI', itens: ['PostgreSQL', 'MySQL', 'Power BI', 'SQL'] },
  { grupo: 'Automação', itens: ['PowerShell', 'Node.js', 'GitHub Actions', 'Bash'] },
  { grupo: 'Software', itens: ['TypeScript', 'React', 'Electron', 'C#', 'Python', 'C'] },
];
